name: Daily Retro Game Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  create-content:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng ffmpeg

      - name: Pick today's game
        run: python src/game_picker.py

      - name: Create today's script
        run: python src/script_generator.py

      - name: Create today's voice
        run: python src/voice_generator.py

      - name: Create today's video
        run: python src/video_generator.py

      - name: Save today's video
        uses: actions/upload-artifact@v4
        with:
          name: retro-tiktok-video
          path: output/todays_video.mp4
          retention-days: 7

      - name: Save script
        uses: actions/upload-artifact@v4
        with:
          name: retro-tiktok-script
          path: output/todays_script.txt
          retention-days: 7
